name: qreki_dart
description: Dart package for 旧暦, the old calendar.
version: 0.1.0
repository: https://github.com/Anishishi/qreki-dart
funding:
  - https://github.com/Anishishi
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - qreki
  - calendar
  - lunar
  - old
  - date
  - time
  - dart
