name: qreki_dart
description: A Dart package for accessing Rokuyo and the old Japanese calendar, '旧暦', enabling easy integration of traditional timekeeping into contemporary apps.
version: 1.0.1
repository: https://github.com/Anishishi/qreki-dart
funding:
  - https://github.com/Anishishi
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - qreki
  - calendar
  - lunar
  - datetime
  - dart
